# Generated by Django 5.0.7 on 2026-03-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_recyclable_listing_coordinates'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collectionrequest',
            index=models.Index(fields=['collector', 'status'], name='cr_collector_status_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionrequest',
            index=models.Index(fields=['household', 'status'], name='cr_household_status_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionrequest',
            index=models.Index(fields=['scheduled_date'], name='cr_scheduled_date_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionrequest',
            index=models.Index(fields=['created_at'], name='cr_created_at_idx'),
        ),
    ]
