# Generated by Django 5.0.7 on 2026-03-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_collectionrequest_cr_collector_status_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collectortransaction',
            index=models.Index(fields=['collector', 'created_at'], name='ct_collector_time_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status', 'created_at'], name='compl_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['reporter', 'status'], name='compl_reporter_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'event_date'], name='ev_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['creator', 'status'], name='ev_creator_status_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['user', 'registration_date'], name='ep_user_regdate_idx'),
        ),
        migrations.AddIndex(
            model_name='illegaldumping',
            index=models.Index(fields=['status', 'reported_at'], name='dump_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='illegaldumping',
            index=models.Index(fields=['reporter', 'status'], name='dump_reporter_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='priceoffer',
            index=models.Index(fields=['listing', 'status'], name='po_listing_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='priceoffer',
            index=models.Index(fields=['recycler', 'status'], name='po_recycler_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='recyclablelisting',
            index=models.Index(fields=['status', 'created_at'], name='rl_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='recyclablelisting',
            index=models.Index(fields=['recycler', 'status'], name='rl_recycler_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='recyclablelisting',
            index=models.Index(fields=['resident', 'status'], name='rl_resident_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='recyclertransaction',
            index=models.Index(fields=['recycler', 'created_at'], name='rt_recycler_time_idx'),
        ),
        migrations.AddIndex(
            model_name='recyclertransaction',
            index=models.Index(fields=['material_type', 'created_at'], name='rt_material_time_idx'),
        ),
        migrations.AddIndex(
            model_name='suspendeduser',
            index=models.Index(fields=['user', 'active'], name='susp_user_active_idx'),
        ),
    ]
